name: Run Python Unit Tests

on: [push, workflow_call]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tensorflow-version: ["2.4.0", "2.6.0", "2.11.0", "2.12.0"]
        python-version: ["3.7", "3.8"]
        exclude:
          - tensorflow-version: "2.4.0"  # tensorflow 2.4 minimum version is 3.7, skip 3.8+
            python-version: "3.8"
          - tensorflow-version: "2.6.0"  # tensorflow 2.6 minimum version is 3.7, skip 3.8+
            python-version: "3.8"
          - tensorflow-version: "3.11.0"  # tensorflow 2.11 minimum version is 3.7, skip 3.8+
            python-version: "3.8"
          - tensorflow-version: "2.12.0"  # tensorflow 2.12 minimum version is 3.8, drop 3.7 and skip 3.9+
            python-version: "3.7"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install tensorflow==${{ matrix.tensorflow-version }}
          pip install -U protobuf==3.20.0 pytest
      - name: Run tests
        run: pytest
