name: Run Python Unit Tests

on: [push, workflow_call]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tensorflow-version: ["2.4.0", "2.6.0", "2.11.0", "2.12.0"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        exclude:
          - tensorflow-version: "2.4.0"  # tensorflow 2.4.0 does not have Python 3.9 and 3.10 support
            python-version: "3.9"
          - tensorflow-version: "2.4.0"
            python-version: "3.10"
          - tensorflow-version: "2.6.0"  # tensorflow 2.6.0 does not have Python 3.10 support
            python-version: "3.10"
          - tensorflow-version: "2.12.0"  # tensorflow 2.12.0 drops Python 3.7 support
            python-version: "3.7"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install tensorflow==${{ matrix.tensorflow-version }}
          pip install -U protobuf==3.20.0 pytest
      - name: Run tests
        run: pytest
