name: Unit tests

on: [push, workflow_call]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        tensorflow-version: ["2.4.0", "2.7.0", "2.12.0"]
        include:
          - tensorflow-version: "2.4.0"  # TensorFlow 2.4 minimum Python is 3.6
            python-version: "3.6"
          - tensorflow-version: "2.7.0"  # TensorFlow 2.7 minimum Python is 3.7
            python-version: "3.7"
          - tensorflow-version: "2.12.0"  # TensorFlow 2.12 minimum Python is 3.8
            python-version: "3.8"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install tensorflow==${{ matrix.tensorflow-version }}
          pip install -U "protobuf<=3.20.0" pytest
      - name: Run tests
        run: pytest
