name: Run Python Unit Tests

on: [push, workflow_call]

jobs:
  tests:
    name: Run tests over matrices
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        tensorflow-variant: ["tensorflow", "tensorflow-cpu", "tensorflow-intel"]
        tensorflow-version: ["2.7", "2.8", "2.9", "2.10", "2.11", "2.12"]
        exclude:
          - os: ubuntu-latest
            tensorflow-variant: "tensorflow-intel"
          - os: macos-latest
            tensorflow-variant: "tensorflow"
          - os: macos-latest
            tensorflow-variant: "tensorflow-intel"
          - os: windows-latest
            tensorflow-variant: "tensorflow"
          - os: windows-latest
            tensorflow-variant: "tensorflow-cpu"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install ${{ matrix.tensorflow-variant }}==${{ matrix.tensorflow-version }}
          pip install pytest
      - name: Run tests
        run: pytest
